name: Deployment
on:
  push:
    branches: [ master ]
jobs: 
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v7
      - name: Build the Docker image
        run: | 
             echo $GITHUB_ACTOR
             echo "Hi"
        
      


