name: HelloWorld
on: 
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.py'
      - '**.yml'
      - "!*.txt"
      - "!README.md"
env:
  WORKFLOW_ENV: Production
jobs:    
  producer:
    environment: QA
    env: 
        JOBS_ENV: Staging
        PORT: ${{ vars.PORT_QA }}
        USERNAME: ${{ secrets.QA_DB_USERNAME }}
    runs-on: ubuntu-latest
    outputs:
        foo: ${{ steps.generate-foo.outputs.foo }}
    steps:
    - name: Say hello
      id: generate-foo
      #env: 
        #ENV: Staging1
      run: |
        foo=ajinkya
        echo "Hello World! $WORKFLOW_ENV"
        echo "Hello World! $JOBS_ENV"
        echo "Hello World! $ENV"
        echo "foo=$foo" >> $GITHUB_OUTPUT
        echo "FOO=$foo" >> $GITHUB_ENV
        echo ${{ env.PORT }}
        echo ${{ env.USERNAME }}
    - name: Inspect values inside producer
      run: | 
           echo "FOO (set via GITHUB_ENV): $FOO" 
           echo "foo (set via GITHUB_OUTPUT): ${{ steps.generate-foo.outputs.foo }}"

  consumer:
    runs-on: ubuntu-latest
    needs: 
        - producer
    steps:
    - name: Say hello
      run: |
        echo "value from producer: ${{ needs.producer.outputs.foo}}"
        echo "FOO in consumer: ${FOO: <UNSET>}"
        

  say-hello-action:
    runs-on: ubuntu-latest
    needs: 
        - consumer
    outputs:
        result: ${{ steps.say-hello-action.outputs.result }}
    steps:
    - uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
