name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print Greeting
        run: |
             echo "Hello World!"
             echo "Multi command"
      - name: Print GoodBye
        run: |
            sleep 5m && echo "Done - Bye!"
      
